# Generated by Django 5.0.4 on 2024-04-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('descricao', models.CharField()),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
